[package]
name = "holmes"
version = "0.2.0"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "holmes"
path = "src/lib.rs"

[[bin]]
name = "gtpctl"
path = "tools/gtpctl.rs"

[[bin]]
name = "bench-board"
path = "tools/bench-board.rs"

[[bin]]
name = "bench-tree"
path = "tools/bench-tree.rs"

[dependencies]
bit-set = "*"
bit-vec = "*"
bufstream = "*"
byteorder = "*"
getopts = "*"
rand = "*"
time = "*"
