[package]
name = "holmes"
version = "0.2.0"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "holmes"
path = "src/lib.rs"

[[bin]]
name = "gtpctl"
path = "tools/gtpctl.rs"

[[bin]]
name = "test-book"
path = "tools/test-book.rs"

[[bin]]
name = "test-sgf"
path = "tools/test-sgf.rs"

[[bin]]
name = "bench-board"
path = "tools/bench-board.rs"

#[[bin]]
#name = "bench-tree"
#path = "tools/bench-tree.rs"

[[bin]]
name = "bench-net"
path = "tools/bench-net.rs"

[[bin]]
name = "filter-gogod-data"
path = "tools/filter-gogod-data.rs"

[[bin]]
name = "preproc-gogod-data"
path = "tools/preproc-gogod-data.rs"

[[bin]]
name = "preproc-kgs-data"
path = "tools/preproc-kgs-data.rs"

[[bin]]
name = "train-simba"
path = "tools/train-simba.rs"

[[bin]]
name = "holmes-gtp"
path = "tools/holmes-gtp.rs"

[dependencies]
bit-set = "*"
bit-vec = "*"
bufstream = "*"
byteorder = "*"
getopts = "*"
rand = "*"
rustc-serialize = "*"
time = "*"

[dependencies.array]
path = "../../rembrandt-project/libarray"

[dependencies.arraydb]
path = "../../rembrandt-project/arraydb"

[dependencies.async]
path = "../../rembrandt-project/libasync"

[dependencies.async_cuda]
path = "../../rembrandt-project/libasync_cuda"

[dependencies.rembrandt]
path = "../../rembrandt-project/rembrandt_new"

[dependencies.statistics_avx2]
path = "libstatistics_avx2"
