[package]
name = "holmes"
version = "0.2.0"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "holmes"
path = "src/lib.rs"

[[bin]]
name = "gtpctl"
path = "tools/gtpctl.rs"

[[bin]]
name = "test-book"
path = "tools/test-book.rs"

[[bin]]
name = "test-sgf"
path = "tools/test-sgf.rs"

[[bin]]
name = "bench-board"
path = "tools/bench-board.rs"

#[[bin]]
#name = "bench-tree"
#path = "tools/bench-tree.rs"

[[bin]]
name = "holmes-gtp"
path = "tools/holmes-gtp.rs"

[dependencies]
bit-set = "*"
bit-vec = "*"
bufstream = "*"
byteorder = "*"
getopts = "*"
rand = "*"
time = "*"

[dependencies.statistics_avx2]
path = "libstatistics_avx2"
